trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          wget "https://sca-downloads.s3.amazonaws.com/cli/2.12.34/ScaResolver-linux64.tar.gz"
      displayName: 'Download sca-resolver'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          tar -xzvf "ScaResolver-linux64.tar.gz"
      displayName: 'unzip sca-resolver'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          rm -rf "ScaResolver-linux64.tar.gz"
      displayName: 'remove tar file'
    - task: Checkmarx AST@3
      inputs:
        CheckmarxService: 'CxOne-Seg'
        projectName: '00252150-ADO-CLI-SCAResolver'
        branchName: 'main'
        tenantName: 'cx_seg'
        additionalParams: --scan-types="sast,sca" --sca-resolver /home/vsts/work/1/s/ScaResolver --sca-resolver-params "--gradle-parameters='-Prepository.proxy.url=123 -Prepository.proxy.username=123 -Prepository.proxy.password=123' --log-level Debug"