trigger:
  branches:
    include:
      - main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: windows-latest  # Changed from ubuntu-latest to windows-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri "https://sca-downloads.s3.amazonaws.com/cli/2.12.34/ScaResolver-win64.zip" -OutFile "ScaResolver-win64.zip"
      displayName: 'Download sca-resolver'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Expand-Archive -Path "ScaResolver-win64.zip" -DestinationPath "$(Build.SourcesDirectory)\ScaResolver"
      displayName: 'Unzip sca-resolver'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Remove-Item -Path "ScaResolver-win64.zip" -Force
      displayName: 'Remove zip file'

    - task: Checkmarx AST@3
      inputs:
        CheckmarxService: 'CxOne-Seg'
        projectName: 'RahulP-Javavulnerable'
        branchName: 'main'
        tenantName: 'cx_seg'
        additionalParams: >
          --sca-resolver "$(Build.SourcesDirectory)\ScaResolver\ScaResolver.exe"
          --sca-resolver-params "--gradle-parameters='-pUSERNAME=abc -pPASSWORD=cba' --log-level Debug"
