trigger:
  branches:
    include:
    - main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          wget "https://sca-downloads.s3.amazonaws.com/cli/2.12.34/ScaResolver-win64.zip"
      displayName: 'Download sca-resolver'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          tar -xzvf "ScaResolver-win64.zip"
      displayName: 'unzip sca-resolver'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          rm -rf "ScaResolver-win64.zip"
      displayName: 'remove tar file'
    - task: Checkmarx AST@3
      inputs:
        CheckmarxService: 'CxOne-Seg'
        projectName: 'RahulP-Javavulnerable'
        branchName: 'main'
        tenantName: 'cx_seg'    
        additionalParams: --sca-resolver /home/vsts/work/1/s/ScaResolver --sca-resolver-params "--gradle-parameters='-pUSERNAME=abc -pPASSWORD=cba'"