trigger:
  branches:
    include:
      - main

stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default   # 👈 Uses self-hosted agent in the 'Default' pool
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri "https://sca-downloads.s3.amazonaws.com/cli/2.12.34/ScaResolver-win64.zip" -OutFile "ScaResolver-win64.zip"
      displayName: 'Download sca-resolver'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Expand-Archive -Path "ScaResolver-win64.zip" -DestinationPath "$(System.DefaultWorkingDirectory)\ScaResolver"
      displayName: 'Unzip sca-resolver'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Remove-Item "ScaResolver-win64.zip" -Force
      displayName: 'Remove ZIP file'

    - task: PowerShell@2
      displayName: 'Run cx scan create (PowerShell)'
      inputs:
        targetType: 'inline'
        script: |
          $sx = 'C:\CLI\ScaResolver-win64\ScaResolver.exe'
          $cmd = "C:\ADO Agent\vsts-agent-win-x64-4.261.0\_work\_tasks\Checkmarx AST_dd862edc-5d88-4d2c-b83b-fff2a695e5c0\3.0.16\node_modules\@checkmarxdev\ast-cli-javascript-wrapper-runtime-cli\dist\main\wrapper\resources\cx.exe scan create --project-name RahulP-Javavulnerable -s C:\CxOnePlugins\Sample-Projects\JavaVulnerableLab\src --branch main --sca-resolver $sx --sca-resolver-params ""--gradle-parameters=-pUSERNAME=abc -pPASSWORD=cba --log-level Debug"""
          Write-Host "Command: $cmd"
          iex $cmd
    - task: Checkmarx AST@3
      inputs:
        CheckmarxService: 'CxOne-Seg'
        projectName: 'RahulP-Javavulnerable'
        branchName: 'main'
        tenantName: 'cx_seg'    
        additionalParams: >
          -s C:\CxOnePlugins\Sample-Projects\JavaVulnerableLab
          --sca-resolver "$(System.DefaultWorkingDirectory)\ScaResolver\ScaResolver.exe" 
          --sca-resolver-params "--gradle-parameters='-pUSERNAME=abc -pPASSWORD=cba'"
